# Generated by Django 4.2.8 on 2025-12-09 20:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_match_weight', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('experience_weight', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('availability_weight', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('past_performance_weight', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_overall_score', models.FloatField(default=60.0, help_text='Score minimo per essere considerato')),
                ('max_candidates_per_run', models.IntegerField(default=20, help_text='Max candidati da restituire')),
                ('promote_diversity', models.BooleanField(default=True, help_text='Promuovi diversità nel team')),
                ('diversity_weight', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferenza Matching',
                'verbose_name_plural': 'Preferenze Matching',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('open', 'Aperto'), ('matching', 'In Matching'), ('active', 'Attivo'), ('completed', 'Completato'), ('cancelled', 'Annullato')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Bassa'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('estimated_duration_weeks', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('team_size_min', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('team_size_max', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titolo Ruolo')),
                ('description', models.TextField(blank=True)),
                ('positions_available', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('positions_filled', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project')),
                ('required_skills', models.ManyToManyField(related_name='project_roles', to='skills.skill')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AIMatchingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(default=dict, help_text='Parametri algoritmo (pesi, filtri, etc)')),
                ('candidates_found', models.IntegerField(default=0)),
                ('candidates_data', models.JSONField(default=list, help_text='Lista candidati con score e dettagli')),
                ('execution_time_seconds', models.FloatField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Creazione'), ('update', 'Modifica'), ('delete', 'Eliminazione'), ('approve', 'Approvazione'), ('reject', 'Rifiuto'), ('ban', 'Ban'), ('unban', 'Rimozione Ban'), ('export', 'Export Dati'), ('matching', 'Esecuzione Matching')], max_length=20)),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('object_repr', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('changes', models.JSONField(default=dict, help_text='Cosa è cambiato')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Azione Admin',
                'verbose_name_plural': 'Azioni Admin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suggested', 'Suggerito da AI'), ('invited', 'Invitato'), ('accepted', 'Accettato'), ('declined', 'Rifiutato'), ('removed', 'Rimosso')], default='invited', max_length=20)),
                ('match_score', models.FloatField(default=0, help_text='Score di match AI (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_reasoning', models.JSONField(default=dict, help_text='Dettagli del perché è stato matchato')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('contribution_notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-invited_at'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProjectRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('required', 'Obbligatoria'), ('preferred', 'Preferita'), ('nice_to_have', 'Nice to Have')], default='required', max_length=20)),
                ('min_proficiency', models.IntegerField(default=3, help_text='Livello minimo richiesto (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('min_years_experience', models.DecimalField(decimal_places=1, default=0, help_text='Anni esperienza minimi', max_digits=4)),
                ('weight', models.IntegerField(default=10, help_text="Peso nell'algoritmo di matching (1-100)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='projects.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'ordering': ['-importance', '-weight'],
                'unique_together': {('project', 'skill')},
            },
        ),
    ]
